name: authui
description: Flutter project to create a login and register UI from dribbble design.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_app_name: ^0.1.0

flutter_app_name:
  name: "Hostels Hub"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  