name: db_project
description: Flutter project to create a login and register UI from dribbble design.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.13
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  firebase: ^9.0.3
  auth: ^8.2.0+02
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  permission_handler: ^10.2.0
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.10
  shared_preferences: ^2.1.0
  location: ^4.4.0
  flutter_bloc: ^8.1.2
  flutter_svg: ^1.0.3
  geocoding: ^2.1.0
  image_picker: ^0.8.7+4
  firebase_storage: ^11.1.1
  cached_network_image: ^3.2.3
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_app_name: ^0.1.0

flutter_app_name:
  name: "Hostels Hub"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  